### ISSUE TITLE
Error when installing from the source

### ISSUE THREAD

**Issue by talhaanwarch** [phillipdupuis/dtale-desktop#15]
Greetings. I am trying to install the dtale-desktop from the source. 
I simply clone the repo to my system, install the dependencies. 
And it is giving me an error while launching.
RuntimeError: Directory 'dtale-desktop-master\dtale_desktop\frontend\build\static' does not exist.

I am using windows 10, python version 3.7

Here is complete traceback

```
Traceback (most recent call last):

  File "<ipython-input-1-af61c54ab04a>", line 2, in <module>
    dtale_desktop.run()

  File "D:\git\dtale-desktop-master\dtale-desktop-master\dtale_desktop\__init__.py", line 62, in run
    from dtale_desktop import app

  File "D:\git\dtale-desktop-master\dtale-desktop-master\dtale_desktop\app.py", line 31, in <module>
    StaticFiles(directory=os.path.join(settings.REACT_APP_DIR, "static")),

  File "C:\Anaconda3\lib\site-packages\starlette\staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
```

# Update
While installing via pip, these files exists

**Comment by phillipdupuis** [comment]
Hi, sorry for taking a while to respond to this! And good catch

The issue is that the react build isn't included on github. You can recreate it yourself via `cd frontend && npm install && npm run build`, but I should make that clearer so people can actually help work on this. I'll leave this open until I update the readme

**Comment by phillipdupuis** [comment]
This should be all set now 😺
